### ISSUE TITLE
Top of UI is broken on non-Mac/left-titlebar-button systems

### ISSUE THREAD

**Issue by akirapink** [davidjroos/obsidian-notswift#6]
![image](https://github.com/davidjroos/obsidian-notswift/assets/33667869/102c4cf2-c016-4f9e-8190-50b12bac54ee)

Observed on:
Obsidian 1.5.12, Linux Mint 21.3 Cinnamon, latest theme version

**Comment by jslpc** [comment]
Broken on macOS as well (using Sequoia Beta 2, if that makes a difference.)

<img width="1916" alt="SCR-20240727-modm" src="https://github.com/user-attachments/assets/243c5854-a651-4ed6-874a-84372223bc1e">

**Comment by davidjroos** [comment]
> ![image](https://private-user-images.githubusercontent.com/33667869/329808052-102c4cf2-c016-4f9e-8190-50b12bac54ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTYxNTAsIm5iZiI6MTcyMjE1NTg1MCwicGF0aCI6Ii8zMzY2Nzg2OS8zMjk4MDgwNTItMTAyYzRjZjItYzAxNi00ZjllLTgxOTAtNTBiMTJiYWM1NGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmODdhMTBmYzQ5YjliYjBmMDhlNzZkZTYwYTg3ZjI4YzBiNWYyMmIzZDM2ZmZmMjBhN2MyOWU4MGNmM2VhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.loh0Lzl9VOW7ingKFOLXDpEm32Es_xcA6tfbBs8ikL0)
> 
> Observed on: Obsidian 1.5.12, Linux Mint 21.3 Cinnamon, latest theme version

This is a collection of quite aggressive changes to get this looking correct in macos and only macos and will very likely break things on other operating systems - sorry!

> Broken on macOS as well (using Sequoia Beta 2, if that makes a difference.)
> <img alt="SCR-20240727-modm" width="1916" src="https://private-user-images.githubusercontent.com/4315025/352777257-243c5854-a651-4ed6-874a-84372223bc1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTYxNTAsIm5iZiI6MTcyMjE1NTg1MCwicGF0aCI6Ii80MzE1MDI1LzM1Mjc3NzI1Ny0yNDNjNTg1NC1hNjUxLTRlZDYtODc0YS04NDM3MjIyM2JjMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMDgzNzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTlhMDQ0NDk5MjNiOTgyM2YwOTFhMmU0ZGRiYjNkZWMwOTcxNWQwOTA5ODdjYmM0YTA1NjQwMWU0MGU5NDQ5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.73v4wBGyLIsA_lBsnQa1-oj04T1zLbap_upGI_SmXMI">

This is how it's supposed to look!

![20240728_204427_CotEditor@2x](https://github.com/user-attachments/assets/8deeb38b-9657-48b1-b045-4260c3d329c2)

**Comment by jslpc** [comment]
Ah! My mistake, sorry!
